name: Crownfall
version: '${version}'

main: org.solocode.crownfall.Crownfall
api-version: '1.21.11'
load: POSTWORLD

authors: [ TheTeleporter9/Solocode ]
website: Program workers to automate complex tasks that machines can't — powered by Create's kinetic network and kept running with a decent meal.

commands:
  start:
    description: Start the camera system
    usage: /start
    aliases: [ cam ]

dependencies:
  bootstrap:

  server:
    ProtocolLib:
      load: BEFORE
      required: true